before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    main: ./cmd/zstdseek
archives:
  - replacements:
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
