builds:
  - id: zstdseek
    main: ./
    dir: ./cmd/zstdseek
    env:
      - CGO_ENABLED=0
    # go tool dist list -json | jq -r '.[] | select(.FirstClass)'
    targets:
      - go_first_class
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^tests:'
      - '^chore:'
      - '^chore\('
