builds:
  - id: zstdseek
    main: ./
    dir: ./cmd/zstdseek
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
