name: ci

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          check-latest: true
      - name: Run coverage
        working-directory: ./pkg
        run: go test -coverprofile=coverage.out -covermode=count
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
