name: golangci-lint
on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          working-directory: ./pkg
